blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/J7b7EscrAs
    about: Please ask and answer questions here.
  - name: Salt-Users Forum
    url: https://groups.google.com/forum/#!forum/salt-users
    about: Please ask and answer questions here.
